{% set version = "3.0.2" %}

package:
  name: invoke
  version: {{ version }}

source:
  fn: invoke-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/i/invoke/invoke-{{ version }}.tar.gz
  sha256: a4613e79ad35b5d9f9781af09452b8d505a3ecdc0169b729bf0426574700f817

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - invoke = invoke.main:program.run
    - inv = invoke.main:program.run

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  # Python imports
  requires:
    - python {{ python_min }}
  imports:
    - invoke
    - invoke.parser
    - invoke.vendor
    - invoke.vendor.fluidity
    - invoke.vendor.lexicon
    # Disabled python version related tests as we cannot do this in noarch packages
    # - invoke.vendor.yaml3

  commands:
    - invoke --help
    - inv --help

about:
  home: http://docs.pyinvoke.org
  dev_url: https://github.com/pyinvoke/invoke
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Pythonic task execution

extra:
  recipe-maintainers:
    - nicoddemus
    - setu4993
