{% set version = "2.1.1" %}

package:
  name: invoke
  version: {{ version }}

source:
  fn: invoke-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/i/invoke/invoke-{{ version }}.tar.gz
  sha256: 7dcf054c4626b89713da650635c29e9dfeb8a1dd0a14edc60bd3e16f751292ff

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - invoke = invoke.main:program.run
    - inv = invoke.main:program.run

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6

test:
  # Python imports
  imports:
    - invoke
    - invoke.parser
    - invoke.vendor
    - invoke.vendor.fluidity
    - invoke.vendor.lexicon
    # Disabled python version related tests as we cannot do this in noarch packages
    # - invoke.vendor.yaml3

  commands:
    - invoke --help
    - inv --help

about:
  home: http://docs.pyinvoke.org
  dev_url: https://github.com/pyinvoke/invoke
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Pythonic task execution

extra:
  recipe-maintainers:
    - nicoddemus
    - setu4993
