appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: s7CkG/DmMJY+QB1l4L2buBfl5Rmv0YumtU6LX0V9gBbyuN5XJnk6+812KB4xicFAA1uAgNjKiiEQcQ+IQQ+F67MICSSfSZ0MSnvUzMIhMkbFGMhQw3wCj/7UCuCz5UdT2KeUQxKzHbpoytHpnu27jYgYdgM9EJgSN+DJKf9RyMCExpnBVVnmGR7sG++qcxSWnvqord/tzhtJXdEK/aT60tH3soSIdIY881VHRpTSYKWn2MXqUL+WvhoFOcTmLMSuWX0QzBnzdvafE8bjz0H+RgwBOn6rF5mN/1IIWxakeSt+Wqp6bqn3XLpelhCkpCz0YbqtBM3p9Hijn5+xjyymIA3R3Q7nT81UKTZYtaqPYLAWk31bAq0nrWrOF6YS19w6NRMzLTw5DJ/qAYEsz2EB+4ekqOgMb0eIJj8i5uCn76RtSpPuHeM/272Sx+8LFc1hhez5CQNGBM2Rfg8CMuSNNmd80CZXFoUOyPMUiY+2HmXUNABAFq5agHTwHa5Fm7EdtFDA2rn8D+ElgsnQPp4sKsGvS/xy4A2pbVCaYP9WtpIGhNFKb3tqe687LZsUU/WOZREY3ZOjAE2RHJkYXTZanikBDS0xcZLGkhZRrYopz3I1NOJiMyq7M9skhKhltgXXdDbWTMQ0G4YlhYEVvUjQZQo7GAfcNFVbfcl2LQ1BwAM=}
provider:
  win: azure
conda_forge_output_validation: true
